export const RESUME_DATA_REQUEST = 'RESUME_DATA_REQUEST';
export const RESUME_DATA_SUCCESS = 'RESUME_DATA_SUCCESS';
export const RESUME_DATA_FAIL = 'RESUME_DATA_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
